### ISSUE TITLE
Peer Review #1

### ISSUE THREAD

**Issue by Tanmay-Shinde** [YisuHou1/Toronto-Police-Budget-Statistics#1]
**Opening statement summary**:
This paper examines the effectiveness of annual budget changes in the Toronto Police and on the crime rate in the city from 2020 to 2023. This paper highlights the inefficacy of the budget changes to reduce crime and improve policing in the city and calls for a need to reconsider how the safety of Toronto's citizens should be facilitated.

**Strong positive points**:
The study examines an interesting topic worthy of research (given the preliminary findings). It effectively makes use of available data by obtaining two separate datasets and aggregating the relevant features from both datasets to prepare the relevant analysis data required for the study. Th author effectively establishes the credibility of both datasets and gives a clear and concise summary of the data collection, cleaning and analysis process. The figures included in the paper also effectively summarize the dataset at hand and fairly support the conclusions drawn from this study.

The project repository is also well structured and the author has included all relevant components of a statistical study as defined by the [Workflow Components](https://tellingstorieswithdata.com/01-introduction.html#workflow-components) of "Telling Stories With Data" (Alexander, 2023). The author has included all relevant sketches, plan for the study, their raw datasets, analysis data as well as a detailed LLM usage statement.

**Critical improvements needed**
1. README File: The README file in the repository includes a general overview of the repository structure and file organization. It would be beneficial to revise the content of the README file to better summarize the project's goals and the analysis conducted, and how other users can make sense of the content and even replicate the project.

2. Conclusion: The conclusion you come to as part of your data analysis might be a little too strong considering you only have data for the past three years in your dataset. You might want to consider relaxing strong remarks you make such as "it is necessary to reconsider how the city budget should be allocated" because there might be so many other factors affecting crime clearance rates and policing policies that have not been taken into consideration in this study. 

Other than these, there is no other aspect of the paper or project repository that need critical changes.

**Suggestions for improvement:**
As mentioned above, I suggest to update the README file to make it more descriptive and including detailed explanation of the project's objectives, goals, outcomes, and key findings. I would also suggest conducting some literature review around the topic about past trends and comparing their results to yours or try obtaining more data through other datasets and incorporating those in your analysis. Your findings and conclusions will gain a lot of credibility if you can back them up with references and citations from other papers that also point out what you concluded in your study. Please consider adding/changing/removing:
1. A project summary with the main goals and findings of the study in the README
2. In your paper, include a separate Conclusion section to state your findings and conclusions rather than it being part of your data analysis section.
3. Highlight the data limitations in your discussion to mention the lack of availability of data over a longer time period.
4. Discuss potential alternative datasets and studies that support your findings.

**Evaluation:**
The topic of research is relevant and interesting, the project repository is well-structured and, the workflow is highly reproducible. However, you would greatly benefit from adding more precise and relevant documentation and also addressing the shortcomings of your data and analysis, and establish the credibility of your conclusions.

Estimated mark:
51/64 ~ 80%

Reason:
The score is calculated based on the given rubric. Overall, the study excels in most grading criterias, but falls short in data and general excellence criterias. The analysis is carried out effectively using the available data and everything is structured properly, but the dataset used is too small to make relevant and practical conclusions. Expanding on the limitations of the dataset and proposing potential future directions could further increase the study's practical value.

**Comment by YisuHou1** [comment]
Thank you for your detailed feedback. It was extremely helpful in my editing process. I added a project summary to the README file, edited my discussion of limitations, and added a discussion of studies on similar topics in the literature review section. I changed the interpretation of my outcome and the conclusions, but I did not create a separate Conclusion section because it is not a primary component of this project.
