### ISSUE TITLE
Peer Review by Onon Burentuvshin

### ISSUE THREAD

**Issue by ononburen** [YisuHou1/Toronto-Police-Budget-Statistics#4]
**Opening statement summary**

This paper focuses on a data set acquired by the City of Toronto that highlights the statistics of police department budgets and crime rates. The author makes a convincing argument that current measures taken by Toronto Police are lackluster and that crime prevention is not an issue of budget. 

**Strong Positive Points**

The paper tells a really strong story in a sense that it fills a gap that current literature leaves with regard to police budget and crime prevention. 

The figures and the organized data are easily able to be followed along and they seem appropriate metrics for measuring the effectiveness of funding and budget when it comes to crime prevention. 

**Critical improvements needed**

The figures in particular are hard to read. Although they are well-intentioned, the numbers are not separated by commas in Tables 1 and 2. 

Figure 1 has a y-axis that would be better served if measured in billions instead of scientific notation. 

**Suggestions for improvement:**

Improving the readability of the figures and tables would be help a lot. 

Also, it would help readers of the author explains some of the variables like the differences between cleared crime and reported crime.  It is a little difficult to understand how the existence of the variable of cleared vs reported crime contributes to the story being told with the data. 

It is a little nitpicky, but, given the data, it is not determined whether budget increases are actually real increases or nominal increases when accounting for inflation. Given the nature of governmental budget allocations, it does take some time to allocate this budget accordingly, so it might be hard to see some changes with 4 years worth of data. I think acknowledging that a weakness of the paper is that it only covers 4 years of data would be appropriate. 

The fact that the data starts from 2020 is a little problematic considering crime would most likely have been low due to Covid-19 and this pandemic affected the years after. For all we know, crime rates and budget allocation might have told a different story prior to 2020. It may be possible that current crime rates are finally reaching a normal level comparable to pre-Covid years. It is hard to tell without more years of data. 

Evaluation:

Title 2/2
Author, date and repo: 2/2
abstract: 4/4
introduction 4/4
data: 6/10
measurement 4/4
prose 6/6
cross references 1/1
captions: 2/2
graphs/tables/etc: 3/4
referencing 0/4
commits 2/2
sketches 2/2
simulation 4/4
tests 4/4
reproducibility 4/4
code style 1/1
general excellence 2/3

Estimated mark: 59/65

91 out of 100.

Reason:
The figures are hard to read at first glance and variables need to be explained for readers to understand the full context of the trend behind police department budgets. Although it does provide a new perspective on the dynamic of crime prevention budgets and crime rates, this narrative is only told through 4 years of data with problematic timing.

**Comment by YisuHou1** [comment]
Thank you for your feedback. Unfortunately, I am unable to change my dataset due to a lack of alternatives, so the issue of too few data points cannot be resolved. However, I have added a discussion of limitations as you suggested. I also changed the scientific notation of the budget graphs to billions, Thank you for pointing that out.
